# Generated by Django 2.0.2 on 2018-10-12 10:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCustomers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='OraraEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NA', max_length=40)),
                ('description', models.TextField()),
                ('venue', models.CharField(default='NA', max_length=40)),
                ('venue_city', models.CharField(blank=True, max_length=40)),
                ('venue_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('venue_lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('website', models.CharField(blank=True, default='#', max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Format(15 digits): '+999999999'.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Contact')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.AddField(
            model_name='eventcustomers',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.OraraEvent'),
        ),
    ]
