# Generated by Django 2.0.2 on 2018-10-12 11:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20181012_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='oraraevent',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='oraraevent',
            name='description',
            field=models.TextField(blank=True, verbose_name='Event Description'),
        ),
        migrations.AlterField(
            model_name='oraraevent',
            name='name',
            field=models.CharField(default='NA', max_length=40, verbose_name='Event Name'),
        ),
    ]
