# Generated by Django 2.0.2 on 2018-10-12 15:16

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20181012_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='oraraevent',
            name='categories',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('NA', 'RANDOM'), ('SP', 'SPORTS'), ('OD', 'OUTDOOR'), ('BK', 'BOOKS'), ('MV', 'MOVIES'), ('PH', 'PHOTOGRAPHY'), ('DT', 'DATING'), ('NL', 'NIGHTLIFE'), ('TH', 'TECHNICAL'), ('UN', 'UNCATEGORIZED')], default='UN', max_length=29),
        ),
    ]
