# Generated by Django 2.0.2 on 2018-10-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_oraraevent_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oraraevent',
            name='photo',
        ),
        migrations.AddField(
            model_name='oraraevent',
            name='image',
            field=models.ImageField(blank=True, upload_to='events', verbose_name='Event Image'),
        ),
    ]
