# Generated by Django 2.0.2 on 2018-11-04 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_eventlikes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventlikes',
            options={'verbose_name': 'Interested', 'verbose_name_plural': 'Interested'},
        ),
    ]
