# Generated by Django 2.0.2 on 2018-10-11 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20181011_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinterests',
            old_name='interests',
            new_name='tags',
        ),
    ]
