# Generated by Django 2.0.2 on 2018-10-11 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20181011_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinterests',
            old_name='tags',
            new_name='interests',
        ),
    ]
