# Generated by Django 2.0.2 on 2018-10-12 07:42

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20181011_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinterests',
            name='interest_choice',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('NA', 'Unknown'), ('SP', 'SPORTS'), ('OD', 'OUTDOOR'), ('BK', 'BOOKS'), ('MV', 'MOVIES'), ('PH', 'PHOTOGRAPHY')], default='NA', max_length=17),
        ),
    ]
