# Generated by Django 2.0.2 on 2018-10-12 07:57

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_userinterests_interest_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinterests',
            name='interest_choice',
        ),
        migrations.RemoveField(
            model_name='userinterests',
            name='interests',
        ),
        migrations.AddField(
            model_name='userinterests',
            name='interests',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('NA', 'RANDOM'), ('SP', 'SPORTS'), ('OD', 'OUTDOOR'), ('BK', 'BOOKS'), ('MV', 'MOVIES'), ('PH', 'PHOTOGRAPHY')], default='NA', max_length=17),
        ),
    ]
