# Generated by Django 2.0.2 on 2018-10-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20181012_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='orarauser',
            name='area',
            field=models.CharField(blank=True, max_length=40, verbose_name='Area'),
        ),
    ]
