# Generated by Django 2.0.2 on 2018-10-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_orarauser_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='orarauser',
            name='area_lat',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='orarauser',
            name='area_lon',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='orarauser',
            name='bio',
            field=models.CharField(blank=True, default='None', max_length=240, verbose_name='Spasshort Description'),
        ),
    ]
