# Generated by Django 2.0.2 on 2018-10-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20181012_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orarauser',
            name='bio',
            field=models.CharField(blank=True, default='None', max_length=240, verbose_name='Short Description'),
        ),
    ]
