# Generated by Django 2.0.2 on 2018-10-19 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20181012_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='orarauser',
            name='status',
            field=models.TextField(default='Available', verbose_name='User status'),
        ),
    ]
