# Generated by Django 2.0.2 on 2018-10-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_orarauser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orarauser',
            name='status',
            field=models.TextField(default='Available', verbose_name='Status'),
        ),
    ]
