# Generated by Django 2.0.2 on 2019-04-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_orarauser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orarauser',
            name='photo',
            field=models.ImageField(default='profiles/default.jpg', upload_to='profiles', verbose_name='Profile photo'),
        ),
    ]
