# Generated by Django 2.0.2 on 2019-04-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_auto_20190420_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orarauser',
            name='gender',
            field=models.CharField(choices=[(('M', 'MALE'), 'Male'), (('F', 'FEMALE'), 'Female'), (('N', 'NEUTRAL'), 'Neutral')], default=('NA', 'UNKNOWN'), max_length=2, verbose_name='Gender'),
        ),
    ]
