# Generated by Django 2.0.2 on 2018-10-21 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flocks', '0002_userbookmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='oraraconnections',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
